services:
  - type: web
    name: alquimista-musical
    env: python
    plan: free
    
    # Mantemos o rootDir, pois é assim que seu projeto está configurado para funcionar.
    # Com rootDir: src, todos os comandos começam DENTRO de /src.
    rootDir: src

    # BUILD COMMAND CORRIGIDO E NA ORDEM CERTA:
    # 1. Instala e builda o frontend PRIMEIRO.
    # 2. Instala as dependências Python DEPOIS.
    buildCommand: |
      set -o pipefail
      cd static && npm install --legacy-peer-deps && npm run build && cd .. && pip install -r requirements.txt
      
    # O START COMMAND está correto para o rootDir: src
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.1"
