services:
  - type: web
    name: alquimista-musical
    env: python
    pythonVersion: "3.10.13"
    plan: free
    
    # Vamos voltar para a configuração que sabemos que é logicamente correta.
    rootDir: src

    # O BUILD COMMAND EM UMA ÚNICA LINHA - A CHAVE MESTRA
    # Esta é a sintaxe que o Render entende.
    buildCommand: "cd .. && pip install -r requirements.txt && cd src/static && npm install --legacy-peer-deps && npm run build"

    # O START COMMAND CORRETO, considerando o rootDir: src
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
