# render.yaml (VERSÃO FINAL E CORRETA)

services:
  - type: web
    name: alquimista-musical
    env: python
    plan: free # O plano gratuito pode hibernar, o que pode afetar websockets.

    # buildCommand CORRIGIDO:
    # 1. Instala as dependências do Python.
    # 2. Entra na pasta 'static' (que agora está na raiz) e constrói o frontend.
    buildCommand: |
      pip install -r requirements.txt
      cd static && npm install && npm run build

    # startCommand CORRIGIDO:
    # Aponta diretamente para o 'main.py' na raiz, usando o objeto 'application'.
    # Simples e direto, sem 'src.' e sem 'PYTHONPATH'.
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:application"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.1"
      # Adicione outras variáveis de ambiente aqui (chaves de API, etc.)
      # Exemplo:
      # - key: MONGO_URI
      #   fromSecret: true # Use o gerenciador de segredos da Render!
      # - key: HF_TOKEN
      #   fromSecret: true
