# "A Planta da Garagem" para o Alquimista Musical no Render
# Versão Final - Respeitando a arquitetura híbrida (FastAPI/Flask)

services:
  - type: web
    name: alquimista-musical
    # Usamos o ambiente Python nativo do Render, que é o mais simples.
    env: python
    # Garantimos o plano gratuito.
    plan: free
    
    # A chave para tudo: Forçamos o Render a usar o Python 3.10.
    # Isso garante que o 'scipy==1.10.1' encontre um 'wheel' pré-compilado
    # e não tente usar a "furadeira" gfortran.
    pythonVersion: "3.10.13"
    rootDir: src  # <--- ADICIONE ESTA LINHA
    
    # Seus comandos de build originais e corretos.
    # Instala as dependências do Python e depois constrói o frontend.
    buildCommand: |
      pip install -r requirements.txt
      cd src/static
      npm install --legacy-peer-deps
      npm run build

    # O comando de start que sabemos que funciona com FastAPI.
    # Ele inicia o Uvicorn, que é o servidor recomendado para FastAPI.
    # O Gunicorn é ótimo, mas o Uvicorn direto é mais simples e evita
    # a camada extra de complexidade que estava causando erros de importação.
    startCommand: python -m uvicorn src.main:application --host 0.0.0.0 --port 10000

    # Definimos as variáveis de ambiente aqui.
    # O 'fromSecret: true' é opcional. Se preferir, pode colocar o valor
    # direto aqui, mas usar o "Secret File" do Render é mais seguro.
    envVars:
      - key: MONGO_URI
        sync: false # 'sync: false' impede que o Render sobrescreva se vc mudar no dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: HUGGING_FACE_SPACE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
