services:
  - type: web
    name: alquimista-musical
    env: python
    plan: free
    
    # O rootDir foi REMOVIDO para garantir que o build comece na raiz do projeto.
    
    buildCommand: |
      set -o pipefail
      cd src/static && npm install --legacy-peer-deps && npm run build && cd .. && pip install -r requirements.txt
      
    # O Start Command precisa do --chdir src porque o rootDir foi removido.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000 --chdir src"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.1"
