services:
  - type: web
    name: alquimista-musical
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd static && npm install && npm run build
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:application"

    # O rootDir foi REMOVIDO para garantir que o build comece na raiz do projeto.
    
    # USAR ESSE DNOVO SE DER ERRADO buildCommand: |
     # set -o pipefail
     # cd src/static && npm install --legacy-peer-deps && npm run build && cd .. && pip install -r requirements.txt
      
    # O Start Command precisa do --chdir src porque o rootDir foi removido.
 # startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
   
    # Srar command funcional no render
    # uvicorn main:app --host 0.0.0.0 --port 10000 --app-dir src
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.1"
