services:
  - type: web
    name: alquimista-musical
    env: python
    plan: free
    
    # Mantemos o rootDir: src, pois esta é a configuração base do seu projeto na Render.
    # Isso força todos os comandos a começarem dentro da pasta /src.
    rootDir: src

    # O Build Command final e correto.
    buildCommand: |
      set -o pipefail
      cd static && npm install --legacy-peer-deps && npm run build && pip install -r ../requirements.txt
      
    # Seu Start Command original, que funciona corretamente com o rootDir: src.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.1"
